### ISSUE TITLE
Discuss and pick one of the two ideas.

### ISSUE THREAD

**Issue by vezwork** [vezwork/dog-ideas#8]
~Flesh the chosen idea out~
~Decide when other todo tasks will be done~
~by Saturday, April 4th, 2020.~

Flesh out idea will be done in #10

**Comment by sharon-wang** [comment]
Chosen idea: write/draw/animate a story through crowdsourced contributions.

The ultimate goal is to collaborate on a project together. This project allows us to do so, without significant complexity in tech/subject matter and liability to users. Taking on a more complicated idea likely means that it will take longer for us to get started on something (i.e. idea 2).

It will take some time to narrow this idea down into something more concrete. Updates to follow.
